name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Zig
        uses: jetsung/setup-zig@v1
      - name: Setup Cargo Lambda
        uses: zerj9/setup-cargo-lambda@v0.1.2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Build and Package
        run: cargo lambda build --release --arm64 --output-format zip
        env:
          RUSTC_WRAPPER: ""
      - name: Deploy via Serverless
        run: npx serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
